/**
 * Created by wangqiong on 2017/2/28.
 */
var datas=[{
    dataId:"000001",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"000002",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"000003",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"000004",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"000005",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000011",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000021",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000031",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000041",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000051",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000012",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000022",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000032",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000042",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000052",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000013",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000023",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000033",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000043",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000053",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000014",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000024",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000034",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000044",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000054",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000015",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000025",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000035",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000045",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000055",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000016",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000026",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000036",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000046",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000056",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
},{
    dataId:"0000017",
    taskno:"201611001",
    batchno:"001",
    employer:"山东电力公司我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字我是一段文字",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"1",
    status:"-1",
    result:"1",
    message:true
},{
    dataId:"0000027",
    taskno:"201611002",
    batchno:"002",
    employer:"山东电力公司",
    plannedStartTime:"",
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"0",
    result:"",
    message:false
},{
    dataId:"0000037",
    taskno:"201611003",
    batchno:"003",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:"",
    endTime:new Date().toLocaleDateString(),
    analysisResult:"",
    status:"1",
    result:"1",
    message:true
},{
    dataId:"0000047",
    taskno:"201611004",
    batchno:"004",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:"",
    analysisResult:"",
    status:"2",
    result:"",
    message:true
},{
    dataId:"0000057",
    taskno:"201611005",
    batchno:"005",
    employer:"山东电力公司",
    plannedStartTime:new Date().toLocaleDateString(),
    startTime:new Date().toLocaleDateString(),
    endTime:new Date().toLocaleDateString(),
    analysisResult:"3",
    status:"",
    result:"3",
    message:false
}];